---
- name: Generate and update admin passwords while storing in bitwarden
  hosts: Cisco
  gather_facts: no
  collections:
    - cisco.ios

  #MUST RUN bw unlock command first!


  
  tasks:
    #running this command first ensures it doesnt generate a false password for a switch It can't connect to.
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      tags:
      - facts
    #generates password with bitwarden and stores the password and username, then moves the object into the networking collection.
    #this local action runs once per switch that ansible targets and triggers the script in the same folder as the play
    - name: Generate Passwords and store in bitwarden. Return the password
      local_action: ansible.builtin.script BWscripted.sh {{ inventory_hostname }} {{ Session }}
      register: output

    #prints the std outputs of the scripts mostly was used for testing the script.
    - name: Debug output
      ansible.builtin.debug:
        var: output
    - name: Debug variable parsing
      debug:
        var: output.stdout_lines[0]
  
    - name: remove admin user
      ios_user:
        name: admin
        state: absent

    - name: re add the admin user with type 8 password
      ios_config:
        lines:
          - username admin privilege 15 algorithm-type sha256 secret {{output.stdout_lines[0]}}

    - name: Re gather facts
      ios_facts:
        gather_subset:
          - config

    - name: Debug ios facts
      debug:
        var: ansible_net_config

    - name: Assert the configuration contains the user line
      assert:
        that:
          - "'username admin privilege 15 secret 8' in ansible_net_config"
        msg: "User configuration failed"
